env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    # TG_CHAT_ID: ENCRYPTED[!7ac99e74abe810b4caaf9dc46b7947a14becade92db6cf893fbf771b115e597df7e19ff5f5c7b38047cf2d2d4385a249!]
    TG_TOKEN: ENCRYPTED[56ec524335ba69413c50889513cea95ea5ac1cc90532318d81d9c10057db4b1d3dbcfc4b315da52414c6862bcb08e256]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "OF Build"
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/faoliveira78/docker:latest
      cpu: 8
      memory: 16G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/upload.sh)"
