env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[505fba0254f594f7fb60e2b068a72f7c15774cc4e08504512f2acb437037cc6a92adfd8fff9f5030f6debe4b4cc4f24f]
    TG_TOKEN: ENCRYPTED[56ec524335ba69413c50889513cea95ea5ac1cc90532318d81d9c10057db4b1d3dbcfc4b315da52414c6862bcb08e256]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "OF Build"
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/faoliveira78/docker:latest
      cpu: 6
      memory: 24G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl https://raw.githubusercontent.com/GunjanSkry/OF-CI/main/scripts/upload.sh)"
